---
title: "Nobel winners"
author: "Rachel Good"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(readr)
library(readxl)
```

Let's first load the data:

```{r label-me1, message=FALSE}
nobel <- read_csv("C:/Users/rgood28/Documents/Data Sci Labs/ae-06-nobels-sales-dataimport/nobel.csv") 
```

Then let's split the data into two:

```{r label-me2, eval=TRUE}
# stem laureates
library(dplyr)
nobel_stem <- nobel %>%
  filter(category %in% c('Physics', 'Medicine', 'Chemistry', 'Economics')) 
```

```{r nonstem, eval=TRUE}
# non-stem laureates
`%notin%` <- Negate(`%in%`)
nobel_nonstem <- nobel %>%
  filter(category %notin% c('Physics', 'Medicine', 'Chemistry', 'Economics'))
```

And finally write out the data:

```{r write_outs}
# add code for writing out the two data frames here
write_csv(nobel_stem, file = "C:/Users/rgood28/Documents/Data Sci Labs/ae-06-nobels-sales-dataimport/nobel-stem.csv")

write_csv(nobel_nonstem, file = "C:/Users/rgood28/Documents/Data Sci Labs/ae-06-nobels-sales-dataimport/nobel-nonstem.csv")
```

## References {#references}
1. Assignment Adapted from [Mine Cetinkaya-Rundel's Data Science in a Box](https://github.com/rstudio-education/datascience-box)